# Generated by Django 5.1.2 on 2024-11-26 03:10

import django.db.models.deletion
import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0014_users_token_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('media', models.CharField(max_length=255, null=True)),
                ('post_id', models.IntegerField(default=posts.models.generate_post_id, primary_key=True, serialize=False, unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
        migrations.CreateModel(
            name='likes',
            fields=[
                ('like_id', models.IntegerField(default=posts.models.likes_id, primary_key=True, serialize=False, unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.posts')),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('comment', models.CharField(max_length=256)),
                ('comment_id', models.IntegerField(default=posts.models.generate_comments_id, primary_key=True, serialize=False, unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.posts')),
            ],
        ),
        migrations.CreateModel(
            name='replies',
            fields=[
                ('reply_id', models.IntegerField(default=-1, primary_key=True, serialize=False)),
                ('comment_id', models.IntegerField()),
                ('reply', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
