# Generated by Django 5.1.2 on 2024-11-11 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='replies',
            fields=[
                ('reply_id', models.IntegerField(default=-1, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('comment_id', models.IntegerField()),
                ('reply', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='posts',
            fields=[
                ('post_id', models.IntegerField(default=-1, primary_key=True, serialize=False)),
                ('media', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('user_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('comment_id', models.IntegerField(default=-1, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('post_id', models.IntegerField()),
                ('comment', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('user_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
                ('post_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.posts')),
            ],
        ),
    ]
