# Generated by Django 5.1.2 on 2024-11-11 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='post_model',
        ),
        migrations.AddField(
            model_name='posts',
            name='user_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
