# Generated by Django 5.1.2 on 2024-11-26 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_replies_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replies',
            name='author',
        ),
    ]
