# Generated by Django 5.1.2 on 2024-11-11 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_comments_post_model_posts_user_id'),
        ('users', '0002_remove_users_follower_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='user_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.users'),
        ),
    ]
