# Generated by Django 5.1.2 on 2024-11-26 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_replies_author'),
        ('users', '0014_users_token_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='replies',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.users'),
            preserve_default=False,
        ),
    ]
