# Generated by Django 5.1.2 on 2024-11-26 04:12

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_comments_comment_id_comments_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='id',
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_id',
            field=models.IntegerField(default=posts.models.generate_comments_id, primary_key=True, serialize=False, unique=True),
        ),
    ]
