# Generated by Django 5.1.2 on 2024-11-11 23:23

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_rename_user_model_comments_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_id',
            field=models.IntegerField(default=posts.models.generate_post_id, primary_key=True, serialize=False, unique=True),
        ),
    ]
