# Generated by Django 5.1.2 on 2024-11-26 04:43

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_comments_id_comments_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replies',
            name='reply_id',
            field=models.IntegerField(default=posts.models.generate_replies_id, primary_key=True, serialize=False, unique=True),
        ),
    ]
