# Generated by Django 5.1.2 on 2024-11-26 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_replies_reply_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replies',
            name='comment_id',
        ),
    ]
