# Generated by Django 5.1.2 on 2024-11-12 00:19

import django.db.models.deletion
import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_posts_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='post_id',
        ),
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='posts.posts'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_id',
            field=models.IntegerField(default=posts.models.generate_comments_id, primary_key=True, serialize=False, unique=True),
        ),
    ]
