# Generated by Django 5.1.2 on 2024-12-03 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dummy_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='post',
        ),
        migrations.DeleteModel(
            name='follow',
        ),
        migrations.DeleteModel(
            name='likes',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='user',
        ),
        migrations.RemoveField(
            model_name='personal_pages',
            name='user',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='user',
        ),
        migrations.DeleteModel(
            name='replies',
        ),
        migrations.DeleteModel(
            name='users',
        ),
        migrations.DeleteModel(
            name='comments',
        ),
        migrations.DeleteModel(
            name='messages',
        ),
        migrations.DeleteModel(
            name='personal_pages',
        ),
        migrations.DeleteModel(
            name='posts',
        ),
    ]
