# Generated by Django 5.1.1 on 2024-09-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dummy_app', '0002_alter_dummy_table_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='client_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('age', models.IntegerField(max_length=45)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='dummy_table',
        ),
    ]
