# Generated by Django 5.1.1 on 2024-10-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dummy_app', '0004_alter_messages_user_alter_personal_pages_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='title',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='username',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='first_name',
            field=models.CharField(default=0, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.CharField(default=0, max_length=45),
            preserve_default=False,
        ),
    ]
