# Generated by Django 5.1.1 on 2024-09-19 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('media', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=45)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.posts')),
            ],
        ),
        migrations.CreateModel(
            name='replies',
            fields=[
                ('reply_id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.comments')),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.users'),
        ),
        migrations.CreateModel(
            name='personal_pages',
            fields=[
                ('page_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.users')),
            ],
        ),
        migrations.CreateModel(
            name='messages',
            fields=[
                ('message_id', models.IntegerField(primary_key=True, serialize=False)),
                ('reciever_id', models.IntegerField()),
                ('text', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.users')),
            ],
        ),
    ]
