# Generated by Django 5.1.1 on 2024-09-19 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='personal_pages',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='replies',
            old_name='comment_id',
            new_name='comment',
        ),
    ]
