# Generated by Django 5.1.1 on 2024-09-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theButton', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummydata',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
