# Generated by Django 5.1.2 on 2024-11-11 22:00

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_users_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.IntegerField(default=users.models.generate_user_id, editable=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
