# Generated by Django 5.1.2 on 2024-12-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_users_token_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='banner_image',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='profile_description',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
