# Generated by Django 5.1.2 on 2024-11-12 16:45

import django.db.models.deletion
import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_alter_users_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='follow',
            fields=[
                ('pk_follow', models.IntegerField(default=profiles.models.generate_follow_pk, primary_key=True, serialize=False, unique=True)),
                ('followee_id', models.IntegerField()),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
