# Generated by Django 5.1.2 on 2024-11-11 02:32

import django.db.models.deletion
import user_messages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_messages',
            fields=[
                ('user_id', models.IntegerField()),
                ('message_id', models.IntegerField(default=user_messages.models.generate_message_id, primary_key=True, serialize=False, unique=True)),
                ('reciever_id', models.IntegerField()),
                ('text', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('user_model', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
