# Generated by Django 5.1.2 on 2024-11-12 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_messages',
            old_name='text',
            new_name='message_text',
        ),
        migrations.RenameField(
            model_name='user_messages',
            old_name='user_model',
            new_name='sender',
        ),
        migrations.RemoveField(
            model_name='user_messages',
            name='user_id',
        ),
    ]
