# Generated by Django 5.1.2 on 2024-11-12 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0002_rename_text_user_messages_message_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_messages',
            old_name='reciever_id',
            new_name='receiver_id',
        ),
    ]
